   service: import-service-cyprushandmade

   custom:
      bucketName: import-service-cyprushandmade
      queueName: catalogItemsQueue

   provider:
      name: aws
      runtime: nodejs14.x
      stage: dev 
      region: 'eu-west-1'
      lambdaHashingVersion: 20201221
      environment:
        SQS_QUEUE_URL: { Ref: ${self:custom.queueName} }

      iamRoleStatements:
         - Effect: "Allow"
           Action:
             - "s3:ListBucket"
           Resource:
             - arn:aws:s3:::${self:custom.bucketName}

         - Effect: "Allow"
           Action:
             - "s3:*"
           Resource:
             - arn:aws:s3:::${self:custom.bucketName}/*
         - Effect: Allow
              Action:
                - sqs:*
              Resource:
                Fn::GetAtt: [ ${self:custom.queueName}, Arn ]

   functions:
      importProductsFile:
          handler: handler.importProductsFile
          events:
            - http:
                method: get
                path: import
                cors: true
                request:
                  parameters:
                    querystrings:
                      name: true

      importFileParser:
          handler: handler.importFileParser
          events:
            - s3:
                bucket: import-service-cyprushandmade
                event: s3:ObjectCreated:*
                rules:
                    - prefix: uploaded/
                existing: true
            
      
      catalogBatchProcess:
          handler: handler.catalogBatchProcess
          events:
            - sqs:
            arn: arn:aws:sqs:region:eu-west-1:${self:custom.queueName}
            batchSize: 5

            # get called every time a message is sent to the queue 
            - sqs:
                arn:
                  Fn::GetAtt:
                    - ${self:custom.queueName}
                    - Arn
     
     resources:
      Resources:
        ${self:custom.queueName}:
          Type: "AWS::SQS::Queue"
          Properties:
            QueueName: ${self:custom.queueName}             

