// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "shop-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "all products received successfully",
            "schema": {
              "$ref": "#/definitions/function"
            }
          },
          "400": {
            "description": "Bad request. Product not found"
          }
        }
      },
      "post": {
        "summary": "addProduct",
        "description": "",
        "operationId": "addProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Product created successfully",
            "schema": {
              "$ref": "#/definitions/{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"description\":{\"type\":\"string\"},\"price\":{\"type\":\"number\"},\"count\":{\"type\":\"number\"}}}"
            }
          },
          "400": {
            "description": "Bad request."
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product received successfully",
            "schema": {
              "$ref": "#/definitions/IProduct"
            }
          },
          "400": {
            "description": "Bad request. Product not found"
          },
          "404": {
            "description": "Product not found"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};